### ISSUE TITLE
Digital Miner produces nuclear craft by products in silk touch mode

### ISSUE THREAD

**Issue by mrmorder** [ftog-thorgal/Unbound#4]
When using silk touch mode on the digital miner you get secondary drops from Lapis and Redstone (only ones i've tested)

You also get them again when breaking the ores later for raw materials using a pickaxe.

I haven't tested but i'm fairly certain you could just place down the silk touched ore again and again to get free secondary drops

**Comment by mrmorder** [comment]
Also affects coal. Seems to be only NuclearCraft secondary drops

**Comment by ftog-thorgal** [comment]
I was able to replicate this issue and reported it here: https://github.com/aidancbrady/Mekanism/issues/4967

**Comment by ftog-thorgal** [comment]
This has been fixed: https://github.com/turbodiesel4598/NuclearCraft/issues/261
