### ISSUE TITLE
Duping Glitch with Simple storage networks

### ISSUE THREAD

**Issue by wiviw5** [ftog-thorgal/Unbound#5]
On the Unbound server on 0.8 Beta and found a strange glitch while crafting with clay and gravel and sand when all the sudden I couldn't put any more items into my system. Later finding out that the entire storage got filled with clay balls. (About 36 Thousand of them) I was able to get rid of them with a trash can and found duped gravel as well on the floor. (About 1700 Gravel) Getting rid of those too. I was crafting grout while it happened and shift clicking stuff in and out of my inventory and the panel and crafting grid.
I really don't know what caused this except that it was a major duping glitch that could dupe an infinite amount of items depending on how much storage you have attached. (Also switching to refined storage because of all the bugs) I will be testing how I did it but seems weird since most issues I have gotten with it has been dispersing items while crafting or crashing (Other bug report) I have no further knowledge of what happened and my system and what is looked like when It happened will be included.
(https://imgur.com/jUL1sM7) Link to setup

**Comment by ftog-thorgal** [comment]
I was not able to replicate this issue on the latest version of Unbound (Simple Storage Network had a few updates that fixed some major bugs since then) so I am closing this issue.
