### ISSUE TITLE
Duplication of bonsai hoppers

### ISSUE THREAD

**Issue by mrmorder** [ftog-thorgal/Unbound#6]
Using an Actually Additions drill on a hopping bonsai drops two. I've tried it with various augments and all result in the same thing. Two drops.

Does not happen with other tools but I didn't test them all. Also does not happen with just your hand.

**Comment by ftog-thorgal** [comment]
I was able to replicate this issue consistently, reported here: https://github.com/Ellpeck/ActuallyAdditions/issues/1041

**Comment by ftog-thorgal** [comment]
This has been fixed by AA
